// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations.LogDbContext
{
    [DbContext(typeof(Data.LogDbContext))]
    [Migration("20251201014522_logs1")]
    partial class logs1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("server.Models.BackupExecution", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("backupPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("currentFileIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("currentFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("currentFilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("endDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("totalFilesToProcess")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("backupPlanId", "startDateTime");

                    b.ToTable("backup_execution");
                });

            modelBuilder.Entity("server.Models.LogEntry", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("backupPlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("executionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<long?>("size")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("executionId");

                    b.HasIndex("backupPlanId", "datetime");

                    b.ToTable("log_entry");
                });
#pragma warning restore 612, 618
        }
    }
}
